#!/bin/bash
#SBATCH --job-name=task1_30n
#SBATCH --time=00:10:00
#SBATCH --mem=16G
#SBATCH --nodes=2
#SBATCH --ntasks=16
#SBATCH --ntasks-per-node=8
#SBATCH --cpus-per-task=1
#SBATCH --partition=defq
#SBATCH --output=task1_30n_%j.out
#SBATCH --error=task1_30n_%j.err

module load openmpi/4.1.5-gcc-11.2.0-ux65npg

if [ ! -f ./task1_blockcyclic ]; then
    mpicc -Wall -O2 task1_blockcyclic.c -o task1_blockcyclic -lm
fi

CSV_OUT="task1_results.csv"
echo "N,MPI_Processes,Comp_Time,Total_Time" > $CSV_OUT

N_VALUES=(
    10000000 12000000 14000000 16000000 18000000
    20000000 22000000 24000000 26000000 28000000
    30000000 32000000 34000000 36000000 38000000
    40000000 42000000 44000000 46000000 48000000
    50000000 52000000 54000000 56000000 58000000
    60000000 62000000 64000000 66000000 68000000
)

for n in "${N_VALUES[@]}"; do
    RUN_OUTPUT=$(srun ./task1_blockcyclic "$n")
    comp_t=$(echo "$RUN_OUTPUT" | grep "Computational time (slowest process):" | awk '{print $(NF-1)}')
    total_t=$(echo "$RUN_OUTPUT" | grep "Total execution time:" | awk '{print $(NF-1)}')
    echo "$n,$SLURM_NTASKS,$comp_t,$total_t" >> $CSV_OUT
done