#!/bin/bash
#SBATCH --job-name=task1_schemes
#SBATCH --time=00:05:00
#SBATCH --mem=16G
#SBATCH --nodes=2
#SBATCH --ntasks=16
#SBATCH --ntasks-per-node=8
#SBATCH --cpus-per-task=1
#SBATCH --partition=defq
#SBATCH --output=task1_schemes_%j.out

module load openmpi/4.1.5-gcc-11.2.0-ux65npg

N_TEST=30000000
CSV="task1_schemes_results.csv"
echo "Scheme,Processes,Comp_Time,Total_Time" > $CSV

for bin in task1_contiguous task1_cyclic task1_blockcyclic; do
    OUT=$(srun ./$bin $N_TEST)
    comp_t=$(echo "$OUT" | grep "Computational time (slowest process):" | awk '{print $(NF-1)}')
    total_t=$(echo "$OUT" | grep "Total execution time:" | awk '{print $(NF-1)}')
    echo "$bin,16,$comp_t,$total_t" >> $CSV
done